### ISSUE TITLE
Add Japan to the country list

### ISSUE THREAD

**Issue by jklukas** [mozilla/gud#112]
AshleyT on Slack requested:

> Japan as a country (this is one of the top countries for FF iOS users)

**Comment by jklukas** [comment]
We currently have an issue that is preventing deploys, but the backend and frontend changes are now in place. This should be live within the next few days.

**Comment by athomasmoz** [comment]
Thanks for adding that!

**Comment by jklukas** [comment]
"Japan" is now available in the country dropdown. See https://growth-stage.bespoke.nonprod.dataops.mozgcp.net/?endDate=2020-09-29&mode=explore&usage=Any%20Fennec%20iOS%20Activity&attributed=%5B%5D&metric=all&os=%5B%5D&language=%5B%5D&country=%5B%22JP%22%5D&channel=%5B%5D&startDate=2017-06-17
