### ISSUE TITLE
Replace "FirefoxConnect" string with "Firefox for Echo Show"

### ISSUE THREAD

**Issue by tdsmith** [mozilla/gud#84]
FirefoxConnect is listed as one of the products; Roland asked me what FirefoxConnect was and I had to do a Github code search to find out. :)

@hamilton

**Comment by jklukas** [comment]
@tdsmith It's also my understanding that FirefoxConnect is associated with Echo Show, but do we have confirmation it's not used for anything else? Can you link me the reference you have for this?

**Comment by tdsmith** [comment]
Only that it's the only mozilla-mobile repo that contains that string: https://github.com/search?q=org%3Amozilla-mobile+FirefoxConnect&type=Code

@liuche Does a claim that FirefoxConnect is exactly Firefox for Echo Show sound right to you?

**Comment by liuche** [comment]
Yes! Firefox Connect was the codename for Firefox Echo Show before the device was announced publicly. We can definitely switch those over.

**Comment by jklukas** [comment]
Thanks @liuche. I will go ahead and PR the frontend change to display "Firefox for Echo Show".
